agent_name = "voicebox-uat-v2"
secret_set = "voicebox-uat-v2-secret"
agent_profile = "agent-1x"
region = "ap-south"
max_session_duration = 900

[git]
repo = "bigappcompany/voicebox-uat"
branch = "dhanush-dev"
subdirectory = "Appzo-VoiceAgent-V2"
dockerfile_path = "Appzo-VoiceAgent-V2/Dockerfile.cloud"

[scaling]
min_agents = 0
max_agents = 5
