agent_name = "voicebox-uat-updated"
secret_set = "voicebox-uat-secret-updated"
agent_profile = "agent-1x"
region = "ap-south"
max_session_duration = 900

[git]
repo = "bigappcompany/voicebox-uat"
branch = "main"
subdirectory = "Appzo-VoiceAgent-V2"
dockerfile_path = "Dockerfile"

[scaling]
  min_agents = 1
  max_agents = 50